name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger deploy on pushes to the main branch (adjust if necessary)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js
        with:
          node-version: '14'  # Specify the Node.js version, adjust if needed

      - name: Install dependencies
        run: |
          npm ci  # Install dependencies using npm ci (this is preferred in CI/CD pipelines)

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20  # Use the Vercel action to deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel Token from GitHub secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel Project ID from GitHub secrets
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Set Vercel Token in the environment
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Set Vercel Project ID in the environment
